question_data = [
 {"category": "General Knowledge",
  "type": "boolean",
  "difficulty": "easy",
  "question": "Video streaming website YouTube was purchased in 2010 entirety by Facebook for US$1.65 billion in stock.",
  "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
  "question": "muaffakkiyetsizlestirebileceklerimizdenmiymissiniz"
              " is the longest word that can be typed using only the first row on a QWERTY keyboard.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
  "question": "You are allowed to sell your soul on eBay.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
  "question": "The color orange is named after the fruit.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
  "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
  "question": "When you cry in space, your tears stick to your face.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
  "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
  "question": "Stagecoach owned 'South West Trains' before losing the rights to FirstGroup and MTR in March of 2017.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
  "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
  "question": "Vietnam's national flag is a red star in front of a yellow background.",
  "correct_answer": "False", "incorrect_answers": ["True"]}
]
